version: '3'


services:
  postgres:
    image: postgres
    shm_size: '4gb'
    container_name: GymbexDbPostgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    driver: local