@url = https://localhost:7291
@activityId = d4bb7aa8-5626-4f37-ab2c-494248bc0d30


###
GET {{url}}/api/activity
###
GET {{url}}/api/activity/{{activityId}}

###
POST {{url}}/api/activity
Content-Type: application/json

{
    "activityName": "Fitness",
    "reservationDateTime": "2023-10-13"
}

###
PUT {{url}}/api/activity
Content-Type: application/json

{
    "activityId": "{{activityId}}",
    "ActivityDate": "2023-10-05"
}

###
DELETE {{url}}/api/activity/{{activityId}}

###
POST {{url}}/api/customer/
Content-Type: application/json

{
    "username": "barlong",
    "password": "secured-password",
    "fullname": "Bartolomeo Pietruszka",
    "email": "bartolo@gymbex.io",
    "phoneNumber": "772226638",
    "ticketId": null
}

